// export { createApp } from './createApp'
export { h } from './h'
export { renderSolts } from './helpers/renderSolts'
export { createTextVNode } from './vnode'
export { getCurrentInstance } from './component'
export {provide, inject} from './apiInject'
export {createRenderer} from './renderer'